name: Build and Run Tests

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 'Build and run test'
        run: ./gradlew clean build

      - name: 'Save test report'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ${{ github.workspace }}/**/build/reports/tests/
